### PR TITLE
Extra info in the Slack notification for talks

### PR DESCRIPTION
**Pull request by r3trofitted**
Duration, leval and preferred month, plus a bit of formating.

Closes parisrb/paris-rb.org#172

### CODE REVIEW

**Comment by r3trofitted** [comment]
⚠️ Completely untested!

**Comment by adrienpoly** [comment]
@btrd I don't see anymore the preview app. Did something change? Or is it because I had to manually enable the workflow?

**Comment by btrd** [comment]
@adrienpoly Indeed the automatic review is not enabled anymore, I don't know why. But you can create a manual review app here https://dashboard.scalingo.com/apps/osc-fr1/rubyparis/review-apps/manual

**Comment by adrienpoly** [comment]
thanks @r3trofitted 
I ll test it live right away!

**Pull request merged**
